package net.minecraft.server;

public class aty {

   public static final atr a;
   public static final atr b;
   public static final awn c;
   public static final atr d;
   public static final atr e;
   public static final atr f;
   public static final atr g;
   public static final atr h;
   public static final avn i;
   public static final bax j;
   public static final avn k;
   public static final bax l;
   public static final bab m;
   public static final atr n;
   public static final atr o;
   public static final atr p;
   public static final atr q;
   public static final atr r;
   public static final atr s;
   public static final axg t;
   public static final axg u;
   public static final atr v;
   public static final atr w;
   public static final atr x;
   public static final atr y;
   public static final atr z;
   public static final atr A;
   public static final atr B;
   public static final atr C;
   public static final atr D;
   public static final atr E;
   public static final bdq F;
   public static final atr G;
   public static final bbh H;
   public static final auw I;
   public static final bdq J;
   public static final bds K;
   public static final atr L;
   public static final bdx M;
   public static final avy N;
   public static final avy O;
   public static final auc P;
   public static final auc Q;
   public static final atr R;
   public static final atr S;
   public static final awq T;
   public static final awq U;
   public static final atr V;
   public static final atr W;
   public static final atr X;
   public static final atr Y;
   public static final atr Z;
   public static final atr aa;
   public static final avx ab;
   public static final atr ac;
   public static final atr ad;
   public static final auj ae;
   public static final azt af;
   public static final atr ag;
   public static final atr ah;
   public static final atr ai;
   public static final atr aj;
   public static final atr ak;
   public static final atr al;
   public static final atr am;
   public static final atr an;
   public static final atr ao;
   public static final atr ap;
   public static final atr aq;
   public static final atr ar;
   public static final atr as;
   public static final atr at;
   public static final atr au;
   public static final atr av;
   public static final atr aw;
   public static final atr ax;
   public static final atr ay;
   public static final atr az;
   public static final atr aA;
   public static final atr aB;
   public static final atr aC;
   public static final atr aD;
   public static final atr aE;
   public static final atr aF;
   public static final atr aG;
   public static final atr aH;
   public static final atr aI;
   public static final atr aJ;
   public static final auf aK;
   public static final atr aL;
   public static final azy aM;
   public static final atr aN;
   public static final atr aO;
   public static final atr aP;
   public static final atr aQ;
   public static final atr aR;
   public static final atr aS;
   public static final atr aT;
   public static final atr aU;
   public static final atr aV;
   public static final atr aW;
   public static final atr aX;
   public static final ayy aY;
   public static final atr aZ;
   public static final atr ba;
   public static final azz bb;
   public static final azz bc;
   public static final atr bd;
   public static final atr be;
   public static final atr bf;
   public static final atr bg;
   public static final atr bh;
   public static final atr bi;
   public static final atr bj;
   public static final atr bk;
   public static final atr bl;
   public static final atr bm;
   public static final atr bn;
   public static final atr bo;
   public static final atr bp;
   public static final atr bq;
   public static final atr br;
   public static final atr bs;
   public static final atr bt;
   public static final atr bu;
   public static final atr bv;
   public static final ayc bw;
   public static final atr bx;
   public static final atr by;
   public static final atr bz;
   public static final atr bA;
   public static final atr bB;
   public static final atr bC;
   public static final atr bD;
   public static final aui bE;
   public static final atr bF;
   public static final atr bG;
   public static final atr bH;
   public static final atr bI;
   public static final atr bJ;
   public static final atr bK;
   public static final awq bL;
   public static final awq bM;
   public static final atr bN;
   public static final atr bO;
   public static final atr bP;
   public static final atr bQ;
   public static final bbt bR;
   public static final atr bS;
   public static final atr bT;
   public static final atr bU;
   public static final atr bV;
   public static final atr bW;
   public static final atr bX;
   public static final atm bY;
   public static final atr bZ;
   public static final atr ca;
   public static final atr cb;
   public static final atr cc;
   public static final atr cd;
   public static final baj ce;
   public static final atr cf;
   public static final atr cg;
   public static final atr ch;
   public static final atr ci;
   public static final aup cj;
   public static final aup ck;
   public static final auv cl;
   public static final auv cm;
   public static final atr cn;
   public static final atr co;
   public static final awx cp;
   public static final atr cq;
   public static final atr cr;
   public static final atr cs;
   public static final atr ct;
   public static final atr cu;
   public static final atr cv;
   public static final atr cw;
   public static final atr cx;
   public static final atr cy;
   public static final atr cz;
   public static final atr cA;
   public static final atr cB;
   public static final atr cC;
   public static final atr cD;
   public static final atr cE;
   public static final avi cF;
   public static final bar cG;
   public static final bas cH;
   public static final atr cI;
   public static final atr cJ;
   public static final atr cK;
   public static final atr cL;
   public static final atr cM;
   public static final atr cN;
   public static final awq cO;
   public static final awq cP;


   private static atr a(String var0) {
      return (atr)atr.c.a(new oa(var0));
   }

   static {
      if(!od.a()) {
         throw new RuntimeException("Accessed Blocks before Bootstrap!");
      } else {
         a = a("air");
         b = a("stone");
         c = (awn)a("grass");
         d = a("dirt");
         e = a("cobblestone");
         f = a("planks");
         g = a("sapling");
         h = a("bedrock");
         i = (avn)a("flowing_water");
         j = (bax)a("water");
         k = (avn)a("flowing_lava");
         l = (bax)a("lava");
         m = (bab)a("sand");
         n = a("gravel");
         o = a("gold_ore");
         p = a("iron_ore");
         q = a("coal_ore");
         r = a("log");
         s = a("log2");
         t = (axg)a("leaves");
         u = (axg)a("leaves2");
         v = a("sponge");
         w = a("glass");
         x = a("lapis_ore");
         y = a("lapis_block");
         z = a("dispenser");
         A = a("sandstone");
         B = a("noteblock");
         C = a("bed");
         D = a("golden_rail");
         E = a("detector_rail");
         F = (bdq)a("sticky_piston");
         G = a("web");
         H = (bbh)a("tallgrass");
         I = (auw)a("deadbush");
         J = (bdq)a("piston");
         K = (bds)a("piston_head");
         L = a("wool");
         M = (bdx)a("piston_extension");
         N = (avy)a("yellow_flower");
         O = (avy)a("red_flower");
         P = (auc)a("brown_mushroom");
         Q = (auc)a("red_mushroom");
         R = a("gold_block");
         S = a("iron_block");
         T = (awq)a("double_stone_slab");
         U = (awq)a("stone_slab");
         V = a("brick_block");
         W = a("tnt");
         X = a("bookshelf");
         Y = a("mossy_cobblestone");
         Z = a("obsidian");
         aa = a("torch");
         ab = (avx)a("fire");
         ac = a("mob_spawner");
         ad = a("oak_stairs");
         ae = (auj)a("chest");
         af = (azt)a("redstone_wire");
         ag = a("diamond_ore");
         ah = a("diamond_block");
         ai = a("crafting_table");
         aj = a("wheat");
         ak = a("farmland");
         al = a("furnace");
         am = a("lit_furnace");
         an = a("standing_sign");
         ao = a("wooden_door");
         ap = a("spruce_door");
         aq = a("birch_door");
         ar = a("jungle_door");
         as = a("acacia_door");
         at = a("dark_oak_door");
         au = a("ladder");
         av = a("rail");
         aw = a("stone_stairs");
         ax = a("wall_sign");
         ay = a("lever");
         az = a("stone_pressure_plate");
         aA = a("iron_door");
         aB = a("wooden_pressure_plate");
         aC = a("redstone_ore");
         aD = a("lit_redstone_ore");
         aE = a("unlit_redstone_torch");
         aF = a("redstone_torch");
         aG = a("stone_button");
         aH = a("snow_layer");
         aI = a("ice");
         aJ = a("snow");
         aK = (auf)a("cactus");
         aL = a("clay");
         aM = (azy)a("reeds");
         aN = a("jukebox");
         aO = a("fence");
         aP = a("spruce_fence");
         aQ = a("birch_fence");
         aR = a("jungle_fence");
         aS = a("dark_oak_fence");
         aT = a("acacia_fence");
         aU = a("pumpkin");
         aV = a("netherrack");
         aW = a("soul_sand");
         aX = a("glowstone");
         aY = (ayy)a("portal");
         aZ = a("lit_pumpkin");
         ba = a("cake");
         bb = (azz)a("unpowered_repeater");
         bc = (azz)a("powered_repeater");
         bd = a("trapdoor");
         be = a("monster_egg");
         bf = a("stonebrick");
         bg = a("brown_mushroom_block");
         bh = a("red_mushroom_block");
         bi = a("iron_bars");
         bj = a("glass_pane");
         bk = a("melon_block");
         bl = a("pumpkin_stem");
         bm = a("melon_stem");
         bn = a("vine");
         bo = a("fence_gate");
         bp = a("spruce_fence_gate");
         bq = a("birch_fence_gate");
         br = a("jungle_fence_gate");
         bs = a("dark_oak_fence_gate");
         bt = a("acacia_fence_gate");
         bu = a("brick_stairs");
         bv = a("stone_brick_stairs");
         bw = (ayc)a("mycelium");
         bx = a("waterlily");
         by = a("nether_brick");
         bz = a("nether_brick_fence");
         bA = a("nether_brick_stairs");
         bB = a("nether_wart");
         bC = a("enchanting_table");
         bD = a("brewing_stand");
         bE = (aui)a("cauldron");
         bF = a("end_portal");
         bG = a("end_portal_frame");
         bH = a("end_stone");
         bI = a("dragon_egg");
         bJ = a("redstone_lamp");
         bK = a("lit_redstone_lamp");
         bL = (awq)a("double_wooden_slab");
         bM = (awq)a("wooden_slab");
         bN = a("cocoa");
         bO = a("sandstone_stairs");
         bP = a("emerald_ore");
         bQ = a("ender_chest");
         bR = (bbt)a("tripwire_hook");
         bS = a("tripwire");
         bT = a("emerald_block");
         bU = a("spruce_stairs");
         bV = a("birch_stairs");
         bW = a("jungle_stairs");
         bX = a("command_block");
         bY = (atm)a("beacon");
         bZ = a("cobblestone_wall");
         ca = a("flower_pot");
         cb = a("carrots");
         cc = a("potatoes");
         cd = a("wooden_button");
         ce = (baj)a("skull");
         cf = a("anvil");
         cg = a("trapped_chest");
         ch = a("light_weighted_pressure_plate");
         ci = a("heavy_weighted_pressure_plate");
         cj = (aup)a("unpowered_comparator");
         ck = (aup)a("powered_comparator");
         cl = (auv)a("daylight_detector");
         cm = (auv)a("daylight_detector_inverted");
         cn = a("redstone_block");
         co = a("quartz_ore");
         cp = (awx)a("hopper");
         cq = a("quartz_block");
         cr = a("quartz_stairs");
         cs = a("activator_rail");
         ct = a("dropper");
         cu = a("stained_hardened_clay");
         cv = a("barrier");
         cw = a("iron_trapdoor");
         cx = a("hay_block");
         cy = a("carpet");
         cz = a("hardened_clay");
         cA = a("coal_block");
         cB = a("packed_ice");
         cC = a("acacia_stairs");
         cD = a("dark_oak_stairs");
         cE = a("slime");
         cF = (avi)a("double_plant");
         cG = (bar)a("stained_glass");
         cH = (bas)a("stained_glass_pane");
         cI = a("prismarine");
         cJ = a("sea_lantern");
         cK = a("standing_banner");
         cL = a("wall_banner");
         cM = a("red_sandstone");
         cN = a("red_sandstone_stairs");
         cO = (awq)a("double_stone_slab2");
         cP = (awq)a("stone_slab2");
      }
   }
}
