package net.minecraft.server;

public class bgl {

   public final float a;
   public final float b;
   public final float c;
   public final float d;
   public final float e;
   public final float f;
   public final float g;
   public final float h;
   public final float i;
   public final float j;
   public final float k;
   public final float l;
   public final float m;
   public final float n;
   public final float o;
   public final float p;
   public final int q;
   public final boolean r;
   public final boolean s;
   public final int t;
   public final boolean u;
   public final boolean v;
   public final boolean w;
   public final boolean x;
   public final boolean y;
   public final boolean z;
   public final boolean A;
   public final int B;
   public final boolean C;
   public final int D;
   public final boolean E;
   public final int F;
   public final int G;
   public final int H;
   public final int I;
   public final int J;
   public final int K;
   public final int L;
   public final int M;
   public final int N;
   public final int O;
   public final int P;
   public final int Q;
   public final int R;
   public final int S;
   public final int T;
   public final int U;
   public final int V;
   public final int W;
   public final int X;
   public final int Y;
   public final int Z;
   public final int aa;
   public final int ab;
   public final int ac;
   public final int ad;
   public final int ae;
   public final int af;
   public final int ag;
   public final int ah;
   public final int ai;
   public final int aj;
   public final int ak;
   public final int al;
   public final int am;
   public final int an;
   public final int ao;
   public final int ap;
   public final int aq;
   public final int ar;
   public final int as;
   public final int at;
   public final int au;
   public final int av;
   public final int aw;
   public final int ax;
   public final int ay;
   public final int az;


   private bgl(bgn var1) {
      this.a = var1.b;
      this.b = var1.c;
      this.c = var1.d;
      this.d = var1.e;
      this.e = var1.f;
      this.f = var1.g;
      this.g = var1.h;
      this.h = var1.i;
      this.i = var1.j;
      this.j = var1.k;
      this.k = var1.l;
      this.l = var1.m;
      this.m = var1.n;
      this.n = var1.o;
      this.o = var1.p;
      this.p = var1.q;
      this.q = var1.r;
      this.r = var1.s;
      this.s = var1.t;
      this.t = var1.u;
      this.u = var1.v;
      this.v = var1.w;
      this.w = var1.x;
      this.x = var1.y;
      this.y = var1.z;
      this.z = var1.A;
      this.A = var1.B;
      this.B = var1.C;
      this.C = var1.D;
      this.D = var1.E;
      this.E = var1.F;
      this.F = var1.G;
      this.G = var1.H;
      this.H = var1.I;
      this.I = var1.J;
      this.J = var1.K;
      this.K = var1.L;
      this.L = var1.M;
      this.M = var1.N;
      this.N = var1.O;
      this.O = var1.P;
      this.P = var1.Q;
      this.Q = var1.R;
      this.R = var1.S;
      this.S = var1.T;
      this.T = var1.U;
      this.U = var1.V;
      this.V = var1.W;
      this.W = var1.X;
      this.X = var1.Y;
      this.Y = var1.Z;
      this.Z = var1.aa;
      this.aa = var1.ab;
      this.ab = var1.ac;
      this.ac = var1.ad;
      this.ad = var1.ae;
      this.ae = var1.af;
      this.af = var1.ag;
      this.ag = var1.ah;
      this.ah = var1.ai;
      this.ai = var1.aj;
      this.aj = var1.ak;
      this.ak = var1.al;
      this.al = var1.am;
      this.am = var1.an;
      this.an = var1.ao;
      this.ao = var1.ap;
      this.ap = var1.aq;
      this.aq = var1.ar;
      this.ar = var1.as;
      this.as = var1.at;
      this.at = var1.au;
      this.au = var1.av;
      this.av = var1.aw;
      this.aw = var1.ax;
      this.ax = var1.ay;
      this.ay = var1.az;
      this.az = var1.aA;
   }

   // $FF: synthetic method
   bgl(bgn var1, bgm var2) {
      this(var1);
   }
}
