package net.minecraft.server;

public class Blocks {

   public static final Block AIR;
   public static final Block STONE;
   public static final BlockGrass GRASS;
   public static final Block DIRT;
   public static final Block COBBLESTONE;
   public static final Block WOOD;
   public static final Block SAPLING;
   public static final Block BEDROCK;
   public static final BlockFlowing WATER;
   public static final BlockStationary STATIONARY_WATER;
   public static final BlockFlowing LAVA;
   public static final BlockStationary STATIONARY_LAVA;
   public static final BlockSand SAND;
   public static final Block GRAVEL;
   public static final Block GOLD_ORE;
   public static final Block IRON_ORE;
   public static final Block COAL_ORE;
   public static final Block LOG;
   public static final Block LOG2;
   public static final BlockLeaves LEAVES;
   public static final BlockLeaves LEAVES2;
   public static final Block SPONGE;
   public static final Block GLASS;
   public static final Block LAPIS_ORE;
   public static final Block LAPIS_BLOCK;
   public static final Block DISPENSER;
   public static final Block SANDSTONE;
   public static final Block NOTE_BLOCK;
   public static final Block BED;
   public static final Block GOLDEN_RAIL;
   public static final Block DETECTOR_RAIL;
   public static final BlockPiston PISTON_STICKEY;
   public static final Block WEB;
   public static final BlockLongGrass LONG_GRASS;
   public static final BlockDeadBush DEAD_BUSH;
   public static final BlockPiston PISTON;
   public static final BlockPistonExtension PISTON_EXTENSION;
   public static final Block WOOL;
   public static final BlockPistonMoving PISTON_MOVING;
   public static final BlockFlowers YELLOW_FLOWER;
   public static final BlockFlowers RED_ROSE;
   public static final BlockPlant BROWN_MUSHROOM;
   public static final BlockPlant RED_MUSHROOM;
   public static final Block GOLD_BLOCK;
   public static final Block IRON_BLOCK;
   public static final BlockStepAbstract DOUBLE_STEP1;
   public static final BlockStepAbstract STEP1;
   public static final Block BRICK;
   public static final Block TNT;
   public static final Block BOOKSHELF;
   public static final Block MOSSY_COBBLESTONE;
   public static final Block OBSIDIAN;
   public static final Block TORCH;
   public static final BlockFire FIRE;
   public static final Block MOB_SPAWNER;
   public static final Block WOOD_STAIRS;
   public static final BlockChest CHEST;
   public static final BlockRedstoneWire REDSTONE_WIRE;
   public static final Block DIAMOND_ORE;
   public static final Block DIAMOND_BLOCK;
   public static final Block CRAFTING_TABLE;
   public static final Block WHEAT;
   public static final Block FARMLAND;
   public static final Block FURNACE;
   public static final Block BURNING_FURNACE;
   public static final Block SIGN_POST;
   public static final Block WOODEN_DOOR;
   public static final Block SPRUCE_DOOR;
   public static final Block BIRCH_DOOR;
   public static final Block JUNGLE_DOOR;
   public static final Block ACACIA_DOOR;
   public static final Block DARK_OAK_DOOR;
   public static final Block LADDER;
   public static final Block RAILS;
   public static final Block COBBLESTONE_STAIRS;
   public static final Block WALL_SIGN;
   public static final Block LEVER;
   public static final Block STONE_PLATE;
   public static final Block IRON_DOOR_BLOCK;
   public static final Block WOOD_PLATE;
   public static final Block REDSTONE_ORE;
   public static final Block GLOWING_REDSTONE_ORE;
   public static final Block REDSTONE_TORCH_OFF;
   public static final Block REDSTONE_TORCH_ON;
   public static final Block STONE_BUTTON;
   public static final Block SNOW;
   public static final Block ICE;
   public static final Block SNOW_BLOCK;
   public static final BlockCactus CACTUS;
   public static final Block CLAY;
   public static final BlockReed SUGAR_CANE_BLOCK;
   public static final Block JUKEBOX;
   public static final Block FENCE;
   public static final Block SPRUCE_FENCE;
   public static final Block BIRCH_FENCE;
   public static final Block JUNGLE_FENCE;
   public static final Block DARK_OAK_FENCE;
   public static final Block ACACIA_FENCE;
   public static final Block PUMPKIN;
   public static final Block NETHERRACK;
   public static final Block SOUL_SAND;
   public static final Block GLOWSTONE;
   public static final BlockPortal PORTAL;
   public static final Block JACK_O_LANTERN;
   public static final Block CAKE;
   public static final BlockRepeater DIODE_OFF;
   public static final BlockRepeater DIODE_ON;
   public static final Block TRAP_DOOR_WOOD;
   public static final Block MONSTER_EGGS;
   public static final Block SMOOTH_BRICK;
   public static final Block BIG_MUSHROOM_1;
   public static final Block BIG_MUSHROOM_2;
   public static final Block IRON_FENCE;
   public static final Block THIN_GLASS;
   public static final Block MELON;
   public static final Block PUMPKIN_STEM;
   public static final Block MELON_STEM;
   public static final Block VINE;
   public static final Block FENCE_GATE;
   public static final Block SPRUCE_FENCE_GATE;
   public static final Block BIRCH_FENCE_GATE;
   public static final Block JUNGLE_FENCE_GATE;
   public static final Block DARK_OAK_FENCE_GATE;
   public static final Block ACACIA_FENCE_GATE;
   public static final Block BRICK_STAIRS;
   public static final Block STONE_STAIRS;
   public static final BlockMycel MYCEL;
   public static final Block WATER_LILY;
   public static final Block NETHER_BRICK;
   public static final Block NETHER_FENCE;
   public static final Block NETHER_BRICK_STAIRS;
   public static final Block NETHER_WART;
   public static final Block ENCHANTMENT_TABLE;
   public static final Block BREWING_STAND;
   public static final BlockCauldron CAULDRON;
   public static final Block ENDER_PORTAL;
   public static final Block ENDER_PORTAL_FRAME;
   public static final Block WHITESTONE;
   public static final Block DRAGON_EGG;
   public static final Block REDSTONE_LAMP_OFF;
   public static final Block REDSTONE_LAMP_ON;
   public static final BlockStepAbstract WOOD_DOUBLE_STEP;
   public static final BlockStepAbstract WOOD_STEP;
   public static final Block COCOA;
   public static final Block SANDSTONE_STAIRS;
   public static final Block EMERALD_ORE;
   public static final Block ENDER_CHEST;
   public static final BlockTripwireHook TRIPWIRE_HOOK;
   public static final Block TRIPWIRE;
   public static final Block EMERALD_BLOCK;
   public static final Block SPRUCE_WOOD_STAIRS;
   public static final Block BIRCH_WOOD_STAIRS;
   public static final Block JUNGLE_WOOD_STAIRS;
   public static final Block COMMAND;
   public static final BlockBeacon BEACON;
   public static final Block COBBLE_WALL;
   public static final Block FLOWER_POT;
   public static final Block CARROTS;
   public static final Block POTATOES;
   public static final Block WOOD_BUTTON;
   public static final BlockSkull SKULL;
   public static final Block ANVIL;
   public static final Block TRAPPED_CHEST;
   public static final Block GOLD_PLATE;
   public static final Block IRON_PLATE;
   public static final BlockRedstoneComparator REDSTONE_COMPARATOR_OFF;
   public static final BlockRedstoneComparator REDSTONE_COMPARATOR_ON;
   public static final BlockDaylightDetector DAYLIGHT_DETECTOR;
   public static final BlockDaylightDetector DAYLIGHT_DETECTOR_INVERTED;
   public static final Block REDSTONE_BLOCK;
   public static final Block QUARTZ_ORE;
   public static final BlockHopper HOPPER;
   public static final Block QUARTZ_BLOCK;
   public static final Block QUARTZ_STAIRS;
   public static final Block ACTIVATOR_RAIL;
   public static final Block DROPPER;
   public static final Block STAINED_HARDENED_CLAY;
   public static final Block BARRIER;
   public static final Block TRAP_DOOR_IRON;
   public static final Block HAY_BLOCK;
   public static final Block CARPET;
   public static final Block HARDENED_CLAY;
   public static final Block COAL_BLOCK;
   public static final Block PACKET_ICE;
   public static final Block ACACIA_STAIRS;
   public static final Block DARK_OAK_STAIRS;
   public static final Block SLIME;
   public static final BlockTallPlant DOUBLE_PLANT;
   public static final BlockStainedGlass STAINED_GLASS;
   public static final BlockStainedGlassPane STAINED_GLASS_PANE;
   public static final Block PRISMARINE;
   public static final Block SEA_LANTERN;
   public static final Block BANNER_STANDING;
   public static final Block BANNER_WALL;
   public static final Block RED_SANDSTONE;
   public static final Block RED_SANDSTONE_STAIRS;
   public static final BlockStepAbstract DOUBLE_STEP2;
   public static final BlockStepAbstract STEP2;


   private static Block a(String var0) {
      return (Block)Block.REGISTRY.a(new RegistryPrepender(var0));
   }

   static {
      if(!DispenserRegistry.a()) {
         throw new RuntimeException("Accessed Blocks before Bootstrap!");
      } else {
         AIR = a("air");
         STONE = a("stone");
         GRASS = (BlockGrass)a("grass");
         DIRT = a("dirt");
         COBBLESTONE = a("cobblestone");
         WOOD = a("planks");
         SAPLING = a("sapling");
         BEDROCK = a("bedrock");
         WATER = (BlockFlowing)a("flowing_water");
         STATIONARY_WATER = (BlockStationary)a("water");
         LAVA = (BlockFlowing)a("flowing_lava");
         STATIONARY_LAVA = (BlockStationary)a("lava");
         SAND = (BlockSand)a("sand");
         GRAVEL = a("gravel");
         GOLD_ORE = a("gold_ore");
         IRON_ORE = a("iron_ore");
         COAL_ORE = a("coal_ore");
         LOG = a("log");
         LOG2 = a("log2");
         LEAVES = (BlockLeaves)a("leaves");
         LEAVES2 = (BlockLeaves)a("leaves2");
         SPONGE = a("sponge");
         GLASS = a("glass");
         LAPIS_ORE = a("lapis_ore");
         LAPIS_BLOCK = a("lapis_block");
         DISPENSER = a("dispenser");
         SANDSTONE = a("sandstone");
         NOTE_BLOCK = a("noteblock");
         BED = a("bed");
         GOLDEN_RAIL = a("golden_rail");
         DETECTOR_RAIL = a("detector_rail");
         PISTON_STICKEY = (BlockPiston)a("sticky_piston");
         WEB = a("web");
         LONG_GRASS = (BlockLongGrass)a("tallgrass");
         DEAD_BUSH = (BlockDeadBush)a("deadbush");
         PISTON = (BlockPiston)a("piston");
         PISTON_EXTENSION = (BlockPistonExtension)a("piston_head");
         WOOL = a("wool");
         PISTON_MOVING = (BlockPistonMoving)a("piston_extension");
         YELLOW_FLOWER = (BlockFlowers)a("yellow_flower");
         RED_ROSE = (BlockFlowers)a("red_flower");
         BROWN_MUSHROOM = (BlockPlant)a("brown_mushroom");
         RED_MUSHROOM = (BlockPlant)a("red_mushroom");
         GOLD_BLOCK = a("gold_block");
         IRON_BLOCK = a("iron_block");
         DOUBLE_STEP1 = (BlockStepAbstract)a("double_stone_slab");
         STEP1 = (BlockStepAbstract)a("stone_slab");
         BRICK = a("brick_block");
         TNT = a("tnt");
         BOOKSHELF = a("bookshelf");
         MOSSY_COBBLESTONE = a("mossy_cobblestone");
         OBSIDIAN = a("obsidian");
         TORCH = a("torch");
         FIRE = (BlockFire)a("fire");
         MOB_SPAWNER = a("mob_spawner");
         WOOD_STAIRS = a("oak_stairs");
         CHEST = (BlockChest)a("chest");
         REDSTONE_WIRE = (BlockRedstoneWire)a("redstone_wire");
         DIAMOND_ORE = a("diamond_ore");
         DIAMOND_BLOCK = a("diamond_block");
         CRAFTING_TABLE = a("crafting_table");
         WHEAT = a("wheat");
         FARMLAND = a("farmland");
         FURNACE = a("furnace");
         BURNING_FURNACE = a("lit_furnace");
         SIGN_POST = a("standing_sign");
         WOODEN_DOOR = a("wooden_door");
         SPRUCE_DOOR = a("spruce_door");
         BIRCH_DOOR = a("birch_door");
         JUNGLE_DOOR = a("jungle_door");
         ACACIA_DOOR = a("acacia_door");
         DARK_OAK_DOOR = a("dark_oak_door");
         LADDER = a("ladder");
         RAILS = a("rail");
         COBBLESTONE_STAIRS = a("stone_stairs");
         WALL_SIGN = a("wall_sign");
         LEVER = a("lever");
         STONE_PLATE = a("stone_pressure_plate");
         IRON_DOOR_BLOCK = a("iron_door");
         WOOD_PLATE = a("wooden_pressure_plate");
         REDSTONE_ORE = a("redstone_ore");
         GLOWING_REDSTONE_ORE = a("lit_redstone_ore");
         REDSTONE_TORCH_OFF = a("unlit_redstone_torch");
         REDSTONE_TORCH_ON = a("redstone_torch");
         STONE_BUTTON = a("stone_button");
         SNOW = a("snow_layer");
         ICE = a("ice");
         SNOW_BLOCK = a("snow");
         CACTUS = (BlockCactus)a("cactus");
         CLAY = a("clay");
         SUGAR_CANE_BLOCK = (BlockReed)a("reeds");
         JUKEBOX = a("jukebox");
         FENCE = a("fence");
         SPRUCE_FENCE = a("spruce_fence");
         BIRCH_FENCE = a("birch_fence");
         JUNGLE_FENCE = a("jungle_fence");
         DARK_OAK_FENCE = a("dark_oak_fence");
         ACACIA_FENCE = a("acacia_fence");
         PUMPKIN = a("pumpkin");
         NETHERRACK = a("netherrack");
         SOUL_SAND = a("soul_sand");
         GLOWSTONE = a("glowstone");
         PORTAL = (BlockPortal)a("portal");
         JACK_O_LANTERN = a("lit_pumpkin");
         CAKE = a("cake");
         DIODE_OFF = (BlockRepeater)a("unpowered_repeater");
         DIODE_ON = (BlockRepeater)a("powered_repeater");
         TRAP_DOOR_WOOD = a("trapdoor");
         MONSTER_EGGS = a("monster_egg");
         SMOOTH_BRICK = a("stonebrick");
         BIG_MUSHROOM_1 = a("brown_mushroom_block");
         BIG_MUSHROOM_2 = a("red_mushroom_block");
         IRON_FENCE = a("iron_bars");
         THIN_GLASS = a("glass_pane");
         MELON = a("melon_block");
         PUMPKIN_STEM = a("pumpkin_stem");
         MELON_STEM = a("melon_stem");
         VINE = a("vine");
         FENCE_GATE = a("fence_gate");
         SPRUCE_FENCE_GATE = a("spruce_fence_gate");
         BIRCH_FENCE_GATE = a("birch_fence_gate");
         JUNGLE_FENCE_GATE = a("jungle_fence_gate");
         DARK_OAK_FENCE_GATE = a("dark_oak_fence_gate");
         ACACIA_FENCE_GATE = a("acacia_fence_gate");
         BRICK_STAIRS = a("brick_stairs");
         STONE_STAIRS = a("stone_brick_stairs");
         MYCEL = (BlockMycel)a("mycelium");
         WATER_LILY = a("waterlily");
         NETHER_BRICK = a("nether_brick");
         NETHER_FENCE = a("nether_brick_fence");
         NETHER_BRICK_STAIRS = a("nether_brick_stairs");
         NETHER_WART = a("nether_wart");
         ENCHANTMENT_TABLE = a("enchanting_table");
         BREWING_STAND = a("brewing_stand");
         CAULDRON = (BlockCauldron)a("cauldron");
         ENDER_PORTAL = a("end_portal");
         ENDER_PORTAL_FRAME = a("end_portal_frame");
         WHITESTONE = a("end_stone");
         DRAGON_EGG = a("dragon_egg");
         REDSTONE_LAMP_OFF = a("redstone_lamp");
         REDSTONE_LAMP_ON = a("lit_redstone_lamp");
         WOOD_DOUBLE_STEP = (BlockStepAbstract)a("double_wooden_slab");
         WOOD_STEP = (BlockStepAbstract)a("wooden_slab");
         COCOA = a("cocoa");
         SANDSTONE_STAIRS = a("sandstone_stairs");
         EMERALD_ORE = a("emerald_ore");
         ENDER_CHEST = a("ender_chest");
         TRIPWIRE_HOOK = (BlockTripwireHook)a("tripwire_hook");
         TRIPWIRE = a("tripwire");
         EMERALD_BLOCK = a("emerald_block");
         SPRUCE_WOOD_STAIRS = a("spruce_stairs");
         BIRCH_WOOD_STAIRS = a("birch_stairs");
         JUNGLE_WOOD_STAIRS = a("jungle_stairs");
         COMMAND = a("command_block");
         BEACON = (BlockBeacon)a("beacon");
         COBBLE_WALL = a("cobblestone_wall");
         FLOWER_POT = a("flower_pot");
         CARROTS = a("carrots");
         POTATOES = a("potatoes");
         WOOD_BUTTON = a("wooden_button");
         SKULL = (BlockSkull)a("skull");
         ANVIL = a("anvil");
         TRAPPED_CHEST = a("trapped_chest");
         GOLD_PLATE = a("light_weighted_pressure_plate");
         IRON_PLATE = a("heavy_weighted_pressure_plate");
         REDSTONE_COMPARATOR_OFF = (BlockRedstoneComparator)a("unpowered_comparator");
         REDSTONE_COMPARATOR_ON = (BlockRedstoneComparator)a("powered_comparator");
         DAYLIGHT_DETECTOR = (BlockDaylightDetector)a("daylight_detector");
         DAYLIGHT_DETECTOR_INVERTED = (BlockDaylightDetector)a("daylight_detector_inverted");
         REDSTONE_BLOCK = a("redstone_block");
         QUARTZ_ORE = a("quartz_ore");
         HOPPER = (BlockHopper)a("hopper");
         QUARTZ_BLOCK = a("quartz_block");
         QUARTZ_STAIRS = a("quartz_stairs");
         ACTIVATOR_RAIL = a("activator_rail");
         DROPPER = a("dropper");
         STAINED_HARDENED_CLAY = a("stained_hardened_clay");
         BARRIER = a("barrier");
         TRAP_DOOR_IRON = a("iron_trapdoor");
         HAY_BLOCK = a("hay_block");
         CARPET = a("carpet");
         HARDENED_CLAY = a("hardened_clay");
         COAL_BLOCK = a("coal_block");
         PACKET_ICE = a("packed_ice");
         ACACIA_STAIRS = a("acacia_stairs");
         DARK_OAK_STAIRS = a("dark_oak_stairs");
         SLIME = a("slime");
         DOUBLE_PLANT = (BlockTallPlant)a("double_plant");
         STAINED_GLASS = (BlockStainedGlass)a("stained_glass");
         STAINED_GLASS_PANE = (BlockStainedGlassPane)a("stained_glass_pane");
         PRISMARINE = a("prismarine");
         SEA_LANTERN = a("sea_lantern");
         BANNER_STANDING = a("standing_banner");
         BANNER_WALL = a("wall_banner");
         RED_SANDSTONE = a("red_sandstone");
         RED_SANDSTONE_STAIRS = a("red_sandstone_stairs");
         DOUBLE_STEP2 = (BlockStepAbstract)a("double_stone_slab2");
         STEP2 = (BlockStepAbstract)a("stone_slab2");
      }
   }
}
