package net.minecraft.server;

public class Items {

   public static final Item IRON_SPADE;
   public static final Item IRON_PICKAXE;
   public static final Item IRON_AXE;
   public static final Item FLINT_AND_STEEL;
   public static final Item APPLE;
   public static final ItemBow BOW;
   public static final Item ARROW;
   public static final Item COAL;
   public static final Item DIAMOND;
   public static final Item IRON_INGOT;
   public static final Item GOLD_INGOT;
   public static final Item IRON_SWORD;
   public static final Item WOOD_SWORD;
   public static final Item WOOD_SPADE;
   public static final Item WOOD_PICKAXE;
   public static final Item WOOD_AXE;
   public static final Item STONE_SWORD;
   public static final Item STONE_SPADE;
   public static final Item STONE_PICKAXE;
   public static final Item STONE_AXE;
   public static final Item DIAMOND_SWORD;
   public static final Item DIAMOND_SPADE;
   public static final Item DIAMOND_PICKAXE;
   public static final Item DIAMOND_AXE;
   public static final Item STICK;
   public static final Item BOWL;
   public static final Item MUSHROOM_SOUP;
   public static final Item GOLD_SWORD;
   public static final Item GOLD_SPADE;
   public static final Item GOLD_PICKAXE;
   public static final Item GOLD_AXE;
   public static final Item STRING;
   public static final Item FEATHER;
   public static final Item SULPHUR;
   public static final Item WOOD_HOE;
   public static final Item STONE_HOE;
   public static final Item IRON_HOE;
   public static final Item DIAMOND_HOE;
   public static final Item GOLD_HOE;
   public static final Item SEEDS;
   public static final Item WHEAT;
   public static final Item BREAD;
   public static final ItemArmor LEATHER_HELMET;
   public static final ItemArmor LEATHER_CHESTPLATE;
   public static final ItemArmor LEATHER_LEGGINGS;
   public static final ItemArmor LEATHER_BOOTS;
   public static final ItemArmor CHAINMAIL_HELMET;
   public static final ItemArmor CHAINMAIL_CHESTPLATE;
   public static final ItemArmor CHAINMAIL_LEGGINGS;
   public static final ItemArmor CHAINMAIL_BOOTS;
   public static final ItemArmor IRON_HELMET;
   public static final ItemArmor IRON_CHESTPLATE;
   public static final ItemArmor IRON_LEGGINGS;
   public static final ItemArmor IRON_BOOTS;
   public static final ItemArmor DIAMOND_HELMET;
   public static final ItemArmor DIAMOND_CHESTPLATE;
   public static final ItemArmor DIAMOND_LEGGINGS;
   public static final ItemArmor DIAMOND_BOOTS;
   public static final ItemArmor GOLD_HELMET;
   public static final ItemArmor GOLD_CHESTPLATE;
   public static final ItemArmor GOLD_LEGGINGS;
   public static final ItemArmor GOLD_BOOTS;
   public static final Item ak;
   public static final Item al;
   public static final Item am;
   public static final Item an;
   public static final Item ao;
   public static final Item ap;
   public static final Item aq;
   public static final Item ar;
   public static final Item as;
   public static final Item at;
   public static final Item au;
   public static final Item av;
   public static final Item BUCKET;
   public static final Item ax;
   public static final Item ay;
   public static final Item az;
   public static final Item aA;
   public static final Item aB;
   public static final Item aC;
   public static final Item aD;
   public static final Item aE;
   public static final Item aF;
   public static final Item aG;
   public static final Item aH;
   public static final Item aI;
   public static final Item aJ;
   public static final Item aK;
   public static final Item aL;
   public static final Item aM;
   public static final Item aN;
   public static final Item aO;
   public static final Item aP;
   public static final Item aQ;
   public static final ItemFishingRod aR;
   public static final Item aS;
   public static final Item aT;
   public static final Item aU;
   public static final Item aV;
   public static final Item aW;
   public static final Item aX;
   public static final Item aY;
   public static final Item aZ;
   public static final Item ba;
   public static final Item bb;
   public static final Item bc;
   public static final ItemWorldMap bd;
   public static final ItemShears be;
   public static final Item bf;
   public static final Item bg;
   public static final Item bh;
   public static final Item bi;
   public static final Item bj;
   public static final Item bk;
   public static final Item bl;
   public static final Item bm;
   public static final Item bn;
   public static final Item bo;
   public static final Item bp;
   public static final Item bq;
   public static final Item br;
   public static final Item bs;
   public static final Item bt;
   public static final Item bu;
   public static final Item bv;
   public static final Item bw;
   public static final Item bx;
   public static final Item by;
   public static final ItemPotion POTION;
   public static final Item bA;
   public static final Item bB;
   public static final Item bC;
   public static final Item bD;
   public static final Item bE;
   public static final Item bF;
   public static final Item bG;
   public static final Item bH;
   public static final Item bI;
   public static final Item bJ;
   public static final Item bK;
   public static final Item bL;
   public static final Item BOOK_AND_QUILL;
   public static final Item WRITTEN_BOOK;
   public static final Item bO;
   public static final Item bP;
   public static final Item bQ;
   public static final Item bR;
   public static final Item bS;
   public static final Item bT;
   public static final Item bU;
   public static final ItemMapEmpty bV;
   public static final Item bW;
   public static final Item bX;
   public static final Item bY;
   public static final Item bZ;
   public static final Item ca;
   public static final Item cb;
   public static final Item cc;
   public static final ItemEnchantedBook cd;
   public static final Item ce;
   public static final Item cf;
   public static final Item cg;
   public static final Item ch;
   public static final Item ci;
   public static final ItemArmorStand cj;
   public static final Item ck;
   public static final Item cl;
   public static final Item cm;
   public static final Item cn;
   public static final Item co;
   public static final Item cp;
   public static final Item cq;
   public static final Item cr;
   public static final Item cs;
   public static final Item ct;
   public static final Item cu;
   public static final Item cv;
   public static final Item cw;
   public static final Item cx;
   public static final Item cy;
   public static final Item cz;
   public static final Item cA;
   public static final Item cB;
   public static final Item cC;
   public static final Item cD;
   public static final Item cE;


   private static Item a(String var0) {
      return (Item)Item.e.a(new RegistryPrepender(var0));
   }

   static {
      if(!DispenserRegistry.a()) {
         throw new RuntimeException("Accessed Items before Bootstrap!");
      } else {
         IRON_SPADE = a("iron_shovel");
         IRON_PICKAXE = a("iron_pickaxe");
         IRON_AXE = a("iron_axe");
         FLINT_AND_STEEL = a("flint_and_steel");
         APPLE = a("apple");
         BOW = (ItemBow)a("bow");
         ARROW = a("arrow");
         COAL = a("coal");
         DIAMOND = a("diamond");
         IRON_INGOT = a("iron_ingot");
         GOLD_INGOT = a("gold_ingot");
         IRON_SWORD = a("iron_sword");
         WOOD_SWORD = a("wooden_sword");
         WOOD_SPADE = a("wooden_shovel");
         WOOD_PICKAXE = a("wooden_pickaxe");
         WOOD_AXE = a("wooden_axe");
         STONE_SWORD = a("stone_sword");
         STONE_SPADE = a("stone_shovel");
         STONE_PICKAXE = a("stone_pickaxe");
         STONE_AXE = a("stone_axe");
         DIAMOND_SWORD = a("diamond_sword");
         DIAMOND_SPADE = a("diamond_shovel");
         DIAMOND_PICKAXE = a("diamond_pickaxe");
         DIAMOND_AXE = a("diamond_axe");
         STICK = a("stick");
         BOWL = a("bowl");
         MUSHROOM_SOUP = a("mushroom_stew");
         GOLD_SWORD = a("golden_sword");
         GOLD_SPADE = a("golden_shovel");
         GOLD_PICKAXE = a("golden_pickaxe");
         GOLD_AXE = a("golden_axe");
         STRING = a("string");
         FEATHER = a("feather");
         SULPHUR = a("gunpowder");
         WOOD_HOE = a("wooden_hoe");
         STONE_HOE = a("stone_hoe");
         IRON_HOE = a("iron_hoe");
         DIAMOND_HOE = a("diamond_hoe");
         GOLD_HOE = a("golden_hoe");
         SEEDS = a("wheat_seeds");
         WHEAT = a("wheat");
         BREAD = a("bread");
         LEATHER_HELMET = (ItemArmor)a("leather_helmet");
         LEATHER_CHESTPLATE = (ItemArmor)a("leather_chestplate");
         LEATHER_LEGGINGS = (ItemArmor)a("leather_leggings");
         LEATHER_BOOTS = (ItemArmor)a("leather_boots");
         CHAINMAIL_HELMET = (ItemArmor)a("chainmail_helmet");
         CHAINMAIL_CHESTPLATE = (ItemArmor)a("chainmail_chestplate");
         CHAINMAIL_LEGGINGS = (ItemArmor)a("chainmail_leggings");
         CHAINMAIL_BOOTS = (ItemArmor)a("chainmail_boots");
         IRON_HELMET = (ItemArmor)a("iron_helmet");
         IRON_CHESTPLATE = (ItemArmor)a("iron_chestplate");
         IRON_LEGGINGS = (ItemArmor)a("iron_leggings");
         IRON_BOOTS = (ItemArmor)a("iron_boots");
         DIAMOND_HELMET = (ItemArmor)a("diamond_helmet");
         DIAMOND_CHESTPLATE = (ItemArmor)a("diamond_chestplate");
         DIAMOND_LEGGINGS = (ItemArmor)a("diamond_leggings");
         DIAMOND_BOOTS = (ItemArmor)a("diamond_boots");
         GOLD_HELMET = (ItemArmor)a("golden_helmet");
         GOLD_CHESTPLATE = (ItemArmor)a("golden_chestplate");
         GOLD_LEGGINGS = (ItemArmor)a("golden_leggings");
         GOLD_BOOTS = (ItemArmor)a("golden_boots");
         ak = a("flint");
         al = a("porkchop");
         am = a("cooked_porkchop");
         an = a("painting");
         ao = a("golden_apple");
         ap = a("sign");
         aq = a("wooden_door");
         ar = a("spruce_door");
         as = a("birch_door");
         at = a("jungle_door");
         au = a("acacia_door");
         av = a("dark_oak_door");
         BUCKET = a("bucket");
         ax = a("water_bucket");
         ay = a("lava_bucket");
         az = a("minecart");
         aA = a("saddle");
         aB = a("iron_door");
         aC = a("redstone");
         aD = a("snowball");
         aE = a("boat");
         aF = a("leather");
         aG = a("milk_bucket");
         aH = a("brick");
         aI = a("clay_ball");
         aJ = a("reeds");
         aK = a("paper");
         aL = a("book");
         aM = a("slime_ball");
         aN = a("chest_minecart");
         aO = a("furnace_minecart");
         aP = a("egg");
         aQ = a("compass");
         aR = (ItemFishingRod)a("fishing_rod");
         aS = a("clock");
         aT = a("glowstone_dust");
         aU = a("fish");
         aV = a("cooked_fish");
         aW = a("dye");
         aX = a("bone");
         aY = a("sugar");
         aZ = a("cake");
         ba = a("bed");
         bb = a("repeater");
         bc = a("cookie");
         bd = (ItemWorldMap)a("filled_map");
         be = (ItemShears)a("shears");
         bf = a("melon");
         bg = a("pumpkin_seeds");
         bh = a("melon_seeds");
         bi = a("beef");
         bj = a("cooked_beef");
         bk = a("chicken");
         bl = a("cooked_chicken");
         bm = a("mutton");
         bn = a("cooked_mutton");
         bo = a("rabbit");
         bp = a("cooked_rabbit");
         bq = a("rabbit_stew");
         br = a("rabbit_foot");
         bs = a("rabbit_hide");
         bt = a("rotten_flesh");
         bu = a("ender_pearl");
         bv = a("blaze_rod");
         bw = a("ghast_tear");
         bx = a("gold_nugget");
         by = a("nether_wart");
         POTION = (ItemPotion)a("potion");
         bA = a("glass_bottle");
         bB = a("spider_eye");
         bC = a("fermented_spider_eye");
         bD = a("blaze_powder");
         bE = a("magma_cream");
         bF = a("brewing_stand");
         bG = a("cauldron");
         bH = a("ender_eye");
         bI = a("speckled_melon");
         bJ = a("spawn_egg");
         bK = a("experience_bottle");
         bL = a("fire_charge");
         BOOK_AND_QUILL = a("writable_book");
         WRITTEN_BOOK = a("written_book");
         bO = a("emerald");
         bP = a("item_frame");
         bQ = a("flower_pot");
         bR = a("carrot");
         bS = a("potato");
         bT = a("baked_potato");
         bU = a("poisonous_potato");
         bV = (ItemMapEmpty)a("map");
         bW = a("golden_carrot");
         bX = a("skull");
         bY = a("carrot_on_a_stick");
         bZ = a("nether_star");
         ca = a("pumpkin_pie");
         cb = a("fireworks");
         cc = a("firework_charge");
         cd = (ItemEnchantedBook)a("enchanted_book");
         ce = a("comparator");
         cf = a("netherbrick");
         cg = a("quartz");
         ch = a("tnt_minecart");
         ci = a("hopper_minecart");
         cj = (ItemArmorStand)a("armor_stand");
         ck = a("iron_horse_armor");
         cl = a("golden_horse_armor");
         cm = a("diamond_horse_armor");
         cn = a("lead");
         co = a("name_tag");
         cp = a("command_block_minecart");
         cq = a("record_13");
         cr = a("record_cat");
         cs = a("record_blocks");
         ct = a("record_chirp");
         cu = a("record_far");
         cv = a("record_mall");
         cw = a("record_mellohi");
         cx = a("record_stal");
         cy = a("record_strad");
         cz = a("record_ward");
         cA = a("record_11");
         cB = a("record_wait");
         cC = a("prismarine_shard");
         cD = a("prismarine_crystals");
         cE = a("banner");
      }
   }
}
