package net.minecraft.server;

public class Items {

   public static final alq a;
   public static final alq b;
   public static final alq c;
   public static final alq d;
   public static final alq e;
   public static final ajz f;
   public static final alq g;
   public static final alq h;
   public static final alq i;
   public static final alq j;
   public static final alq k;
   public static final alq l;
   public static final alq m;
   public static final alq n;
   public static final alq o;
   public static final alq p;
   public static final alq q;
   public static final alq r;
   public static final alq s;
   public static final alq t;
   public static final alq u;
   public static final alq v;
   public static final alq w;
   public static final alq x;
   public static final alq y;
   public static final alq z;
   public static final alq A;
   public static final alq B;
   public static final alq C;
   public static final alq D;
   public static final alq E;
   public static final alq F;
   public static final alq G;
   public static final alq H;
   public static final alq I;
   public static final alq J;
   public static final alq K;
   public static final alq L;
   public static final alq M;
   public static final alq N;
   public static final alq O;
   public static final alq P;
   public static final ajn Q;
   public static final ajn R;
   public static final ajn S;
   public static final ajn T;
   public static final ajn U;
   public static final ajn V;
   public static final ajn W;
   public static final ajn X;
   public static final ajn Y;
   public static final ajn Z;
   public static final ajn aa;
   public static final ajn ab;
   public static final ajn ac;
   public static final ajn ad;
   public static final ajn ae;
   public static final ajn af;
   public static final ajn ag;
   public static final ajn ah;
   public static final ajn ai;
   public static final ajn aj;
   public static final alq ak;
   public static final alq al;
   public static final alq am;
   public static final alq an;
   public static final alq ao;
   public static final alq ap;
   public static final alq aq;
   public static final alq ar;
   public static final alq as;
   public static final alq at;
   public static final alq au;
   public static final alq av;
   public static final alq aw;
   public static final alq ax;
   public static final alq ay;
   public static final alq az;
   public static final alq aA;
   public static final alq aB;
   public static final alq aC;
   public static final alq aD;
   public static final alq aE;
   public static final alq aF;
   public static final alq aG;
   public static final alq aH;
   public static final alq aI;
   public static final alq aJ;
   public static final alq aK;
   public static final alq aL;
   public static final alq aM;
   public static final alq aN;
   public static final alq aO;
   public static final alq aP;
   public static final alq aQ;
   public static final alj aR;
   public static final alq aS;
   public static final alq aT;
   public static final alq aU;
   public static final alq aV;
   public static final alq aW;
   public static final alq aX;
   public static final alq aY;
   public static final alq aZ;
   public static final alq ba;
   public static final alq bb;
   public static final alq bc;
   public static final amn bd;
   public static final and be;
   public static final alq bf;
   public static final alq bg;
   public static final alq bh;
   public static final alq bi;
   public static final alq bj;
   public static final alq bk;
   public static final alq bl;
   public static final alq bm;
   public static final alq bn;
   public static final alq bo;
   public static final alq bp;
   public static final alq bq;
   public static final alq br;
   public static final alq bs;
   public static final alq bt;
   public static final alq bu;
   public static final alq bv;
   public static final alq bw;
   public static final alq bx;
   public static final alq by;
   public static final amw bz;
   public static final alq bA;
   public static final alq bB;
   public static final alq bC;
   public static final alq bD;
   public static final alq bE;
   public static final alq bF;
   public static final alq bG;
   public static final alq bH;
   public static final alq bI;
   public static final alq bJ;
   public static final alq bK;
   public static final alq bL;
   public static final alq bM;
   public static final alq bN;
   public static final alq bO;
   public static final alq bP;
   public static final alq bQ;
   public static final alq bR;
   public static final alq bS;
   public static final alq bT;
   public static final alq bU;
   public static final akz bV;
   public static final alq bW;
   public static final alq bX;
   public static final alq bY;
   public static final alq bZ;
   public static final alq ca;
   public static final alq cb;
   public static final alq cc;
   public static final ala cd;
   public static final alq ce;
   public static final alq cf;
   public static final alq cg;
   public static final alq ch;
   public static final alq ci;
   public static final ajq cj;
   public static final alq ck;
   public static final alq cl;
   public static final alq cm;
   public static final alq cn;
   public static final alq co;
   public static final alq cp;
   public static final alq cq;
   public static final alq cr;
   public static final alq cs;
   public static final alq ct;
   public static final alq cu;
   public static final alq cv;
   public static final alq cw;
   public static final alq cx;
   public static final alq cy;
   public static final alq cz;
   public static final alq cA;
   public static final alq cB;
   public static final alq cC;
   public static final alq cD;
   public static final alq cE;


   private static alq a(String var0) {
      return (alq)alq.e.a(new RegistryMaterials(var0));
   }

   static {
      if(!DispenserRegistry.a()) {
         throw new RuntimeException("Accessed Items before Bootstrap!");
      } else {
         a = a("iron_shovel");
         b = a("iron_pickaxe");
         c = a("iron_axe");
         d = a("flint_and_steel");
         e = a("apple");
         f = (ajz)a("bow");
         g = a("arrow");
         h = a("coal");
         i = a("diamond");
         j = a("iron_ingot");
         k = a("gold_ingot");
         l = a("iron_sword");
         m = a("wooden_sword");
         n = a("wooden_shovel");
         o = a("wooden_pickaxe");
         p = a("wooden_axe");
         q = a("stone_sword");
         r = a("stone_shovel");
         s = a("stone_pickaxe");
         t = a("stone_axe");
         u = a("diamond_sword");
         v = a("diamond_shovel");
         w = a("diamond_pickaxe");
         x = a("diamond_axe");
         y = a("stick");
         z = a("bowl");
         A = a("mushroom_stew");
         B = a("golden_sword");
         C = a("golden_shovel");
         D = a("golden_pickaxe");
         E = a("golden_axe");
         F = a("string");
         G = a("feather");
         H = a("gunpowder");
         I = a("wooden_hoe");
         J = a("stone_hoe");
         K = a("iron_hoe");
         L = a("diamond_hoe");
         M = a("golden_hoe");
         N = a("wheat_seeds");
         O = a("wheat");
         P = a("bread");
         Q = (ajn)a("leather_helmet");
         R = (ajn)a("leather_chestplate");
         S = (ajn)a("leather_leggings");
         T = (ajn)a("leather_boots");
         U = (ajn)a("chainmail_helmet");
         V = (ajn)a("chainmail_chestplate");
         W = (ajn)a("chainmail_leggings");
         X = (ajn)a("chainmail_boots");
         Y = (ajn)a("iron_helmet");
         Z = (ajn)a("iron_chestplate");
         aa = (ajn)a("iron_leggings");
         ab = (ajn)a("iron_boots");
         ac = (ajn)a("diamond_helmet");
         ad = (ajn)a("diamond_chestplate");
         ae = (ajn)a("diamond_leggings");
         af = (ajn)a("diamond_boots");
         ag = (ajn)a("golden_helmet");
         ah = (ajn)a("golden_chestplate");
         ai = (ajn)a("golden_leggings");
         aj = (ajn)a("golden_boots");
         ak = a("flint");
         al = a("porkchop");
         am = a("cooked_porkchop");
         an = a("painting");
         ao = a("golden_apple");
         ap = a("sign");
         aq = a("wooden_door");
         ar = a("spruce_door");
         as = a("birch_door");
         at = a("jungle_door");
         au = a("acacia_door");
         av = a("dark_oak_door");
         aw = a("bucket");
         ax = a("water_bucket");
         ay = a("lava_bucket");
         az = a("minecart");
         aA = a("saddle");
         aB = a("iron_door");
         aC = a("redstone");
         aD = a("snowball");
         aE = a("boat");
         aF = a("leather");
         aG = a("milk_bucket");
         aH = a("brick");
         aI = a("clay_ball");
         aJ = a("reeds");
         aK = a("paper");
         aL = a("book");
         aM = a("slime_ball");
         aN = a("chest_minecart");
         aO = a("furnace_minecart");
         aP = a("egg");
         aQ = a("compass");
         aR = (alj)a("fishing_rod");
         aS = a("clock");
         aT = a("glowstone_dust");
         aU = a("fish");
         aV = a("cooked_fish");
         aW = a("dye");
         aX = a("bone");
         aY = a("sugar");
         aZ = a("cake");
         ba = a("bed");
         bb = a("repeater");
         bc = a("cookie");
         bd = (amn)a("filled_map");
         be = (and)a("shears");
         bf = a("melon");
         bg = a("pumpkin_seeds");
         bh = a("melon_seeds");
         bi = a("beef");
         bj = a("cooked_beef");
         bk = a("chicken");
         bl = a("cooked_chicken");
         bm = a("mutton");
         bn = a("cooked_mutton");
         bo = a("rabbit");
         bp = a("cooked_rabbit");
         bq = a("rabbit_stew");
         br = a("rabbit_foot");
         bs = a("rabbit_hide");
         bt = a("rotten_flesh");
         bu = a("ender_pearl");
         bv = a("blaze_rod");
         bw = a("ghast_tear");
         bx = a("gold_nugget");
         by = a("nether_wart");
         bz = (amw)a("potion");
         bA = a("glass_bottle");
         bB = a("spider_eye");
         bC = a("fermented_spider_eye");
         bD = a("blaze_powder");
         bE = a("magma_cream");
         bF = a("brewing_stand");
         bG = a("cauldron");
         bH = a("ender_eye");
         bI = a("speckled_melon");
         bJ = a("spawn_egg");
         bK = a("experience_bottle");
         bL = a("fire_charge");
         bM = a("writable_book");
         bN = a("written_book");
         bO = a("emerald");
         bP = a("item_frame");
         bQ = a("flower_pot");
         bR = a("carrot");
         bS = a("potato");
         bT = a("baked_potato");
         bU = a("poisonous_potato");
         bV = (akz)a("map");
         bW = a("golden_carrot");
         bX = a("skull");
         bY = a("carrot_on_a_stick");
         bZ = a("nether_star");
         ca = a("pumpkin_pie");
         cb = a("fireworks");
         cc = a("firework_charge");
         cd = (ala)a("enchanted_book");
         ce = a("comparator");
         cf = a("netherbrick");
         cg = a("quartz");
         ch = a("tnt_minecart");
         ci = a("hopper_minecart");
         cj = (ajq)a("armor_stand");
         ck = a("iron_horse_armor");
         cl = a("golden_horse_armor");
         cm = a("diamond_horse_armor");
         cn = a("lead");
         co = a("name_tag");
         cp = a("command_block_minecart");
         cq = a("record_13");
         cr = a("record_cat");
         cs = a("record_blocks");
         ct = a("record_chirp");
         cu = a("record_far");
         cv = a("record_mall");
         cw = a("record_mellohi");
         cx = a("record_stal");
         cy = a("record_strad");
         cz = a("record_ward");
         cA = a("record_11");
         cB = a("record_wait");
         cC = a("prismarine_shard");
         cD = a("prismarine_crystals");
         cE = a("banner");
      }
   }
}
