package net.minecraft.server;

public class Items {

   public static final Item a;
   public static final Item b;
   public static final Item c;
   public static final Item d;
   public static final Item e;
   public static final ItemBow f;
   public static final Item g;
   public static final Item h;
   public static final Item i;
   public static final Item j;
   public static final Item k;
   public static final Item l;
   public static final Item m;
   public static final Item n;
   public static final Item o;
   public static final Item p;
   public static final Item q;
   public static final Item r;
   public static final Item s;
   public static final Item t;
   public static final Item u;
   public static final Item v;
   public static final Item w;
   public static final Item x;
   public static final Item y;
   public static final Item z;
   public static final Item A;
   public static final Item B;
   public static final Item C;
   public static final Item D;
   public static final Item E;
   public static final Item F;
   public static final Item G;
   public static final Item H;
   public static final Item I;
   public static final Item J;
   public static final Item K;
   public static final Item L;
   public static final Item M;
   public static final Item N;
   public static final Item O;
   public static final Item P;
   public static final ItemArmor Q;
   public static final ItemArmor R;
   public static final ItemArmor S;
   public static final ItemArmor T;
   public static final ItemArmor U;
   public static final ItemArmor V;
   public static final ItemArmor W;
   public static final ItemArmor X;
   public static final ItemArmor Y;
   public static final ItemArmor Z;
   public static final ItemArmor aa;
   public static final ItemArmor ab;
   public static final ItemArmor ac;
   public static final ItemArmor ad;
   public static final ItemArmor ae;
   public static final ItemArmor af;
   public static final ItemArmor ag;
   public static final ItemArmor ah;
   public static final ItemArmor ai;
   public static final ItemArmor aj;
   public static final Item ak;
   public static final Item al;
   public static final Item am;
   public static final Item an;
   public static final Item ao;
   public static final Item ap;
   public static final Item aq;
   public static final Item ar;
   public static final Item as;
   public static final Item at;
   public static final Item au;
   public static final Item av;
   public static final Item BUCKET;
   public static final Item ax;
   public static final Item ay;
   public static final Item az;
   public static final Item aA;
   public static final Item aB;
   public static final Item aC;
   public static final Item aD;
   public static final Item aE;
   public static final Item aF;
   public static final Item aG;
   public static final Item aH;
   public static final Item aI;
   public static final Item aJ;
   public static final Item aK;
   public static final Item aL;
   public static final Item aM;
   public static final Item aN;
   public static final Item aO;
   public static final Item aP;
   public static final Item aQ;
   public static final ItemFishingRod aR;
   public static final Item aS;
   public static final Item aT;
   public static final Item aU;
   public static final Item aV;
   public static final Item aW;
   public static final Item aX;
   public static final Item aY;
   public static final Item aZ;
   public static final Item ba;
   public static final Item bb;
   public static final Item bc;
   public static final ItemWorldMap bd;
   public static final ItemShears be;
   public static final Item bf;
   public static final Item bg;
   public static final Item bh;
   public static final Item bi;
   public static final Item bj;
   public static final Item bk;
   public static final Item bl;
   public static final Item bm;
   public static final Item bn;
   public static final Item bo;
   public static final Item bp;
   public static final Item bq;
   public static final Item br;
   public static final Item bs;
   public static final Item bt;
   public static final Item bu;
   public static final Item bv;
   public static final Item bw;
   public static final Item bx;
   public static final Item by;
   public static final ItemPotion POTION;
   public static final Item bA;
   public static final Item bB;
   public static final Item bC;
   public static final Item bD;
   public static final Item bE;
   public static final Item bF;
   public static final Item bG;
   public static final Item bH;
   public static final Item bI;
   public static final Item bJ;
   public static final Item bK;
   public static final Item bL;
   public static final Item BOOK_AND_QUILL;
   public static final Item WRITTEN_BOOK;
   public static final Item bO;
   public static final Item bP;
   public static final Item bQ;
   public static final Item bR;
   public static final Item bS;
   public static final Item bT;
   public static final Item bU;
   public static final ItemMapEmpty bV;
   public static final Item bW;
   public static final Item bX;
   public static final Item bY;
   public static final Item bZ;
   public static final Item ca;
   public static final Item cb;
   public static final Item cc;
   public static final ItemEnchantedBook cd;
   public static final Item ce;
   public static final Item cf;
   public static final Item cg;
   public static final Item ch;
   public static final Item ci;
   public static final ItemArmorStand cj;
   public static final Item ck;
   public static final Item cl;
   public static final Item cm;
   public static final Item cn;
   public static final Item co;
   public static final Item cp;
   public static final Item cq;
   public static final Item cr;
   public static final Item cs;
   public static final Item ct;
   public static final Item cu;
   public static final Item cv;
   public static final Item cw;
   public static final Item cx;
   public static final Item cy;
   public static final Item cz;
   public static final Item cA;
   public static final Item cB;
   public static final Item cC;
   public static final Item cD;
   public static final Item cE;


   private static Item a(String var0) {
      return (Item)Item.e.a(new RegistryPrepender(var0));
   }

   static {
      if(!DispenserRegistry.a()) {
         throw new RuntimeException("Accessed Items before Bootstrap!");
      } else {
         a = a("iron_shovel");
         b = a("iron_pickaxe");
         c = a("iron_axe");
         d = a("flint_and_steel");
         e = a("apple");
         f = (ItemBow)a("bow");
         g = a("arrow");
         h = a("coal");
         i = a("diamond");
         j = a("iron_ingot");
         k = a("gold_ingot");
         l = a("iron_sword");
         m = a("wooden_sword");
         n = a("wooden_shovel");
         o = a("wooden_pickaxe");
         p = a("wooden_axe");
         q = a("stone_sword");
         r = a("stone_shovel");
         s = a("stone_pickaxe");
         t = a("stone_axe");
         u = a("diamond_sword");
         v = a("diamond_shovel");
         w = a("diamond_pickaxe");
         x = a("diamond_axe");
         y = a("stick");
         z = a("bowl");
         A = a("mushroom_stew");
         B = a("golden_sword");
         C = a("golden_shovel");
         D = a("golden_pickaxe");
         E = a("golden_axe");
         F = a("string");
         G = a("feather");
         H = a("gunpowder");
         I = a("wooden_hoe");
         J = a("stone_hoe");
         K = a("iron_hoe");
         L = a("diamond_hoe");
         M = a("golden_hoe");
         N = a("wheat_seeds");
         O = a("wheat");
         P = a("bread");
         Q = (ItemArmor)a("leather_helmet");
         R = (ItemArmor)a("leather_chestplate");
         S = (ItemArmor)a("leather_leggings");
         T = (ItemArmor)a("leather_boots");
         U = (ItemArmor)a("chainmail_helmet");
         V = (ItemArmor)a("chainmail_chestplate");
         W = (ItemArmor)a("chainmail_leggings");
         X = (ItemArmor)a("chainmail_boots");
         Y = (ItemArmor)a("iron_helmet");
         Z = (ItemArmor)a("iron_chestplate");
         aa = (ItemArmor)a("iron_leggings");
         ab = (ItemArmor)a("iron_boots");
         ac = (ItemArmor)a("diamond_helmet");
         ad = (ItemArmor)a("diamond_chestplate");
         ae = (ItemArmor)a("diamond_leggings");
         af = (ItemArmor)a("diamond_boots");
         ag = (ItemArmor)a("golden_helmet");
         ah = (ItemArmor)a("golden_chestplate");
         ai = (ItemArmor)a("golden_leggings");
         aj = (ItemArmor)a("golden_boots");
         ak = a("flint");
         al = a("porkchop");
         am = a("cooked_porkchop");
         an = a("painting");
         ao = a("golden_apple");
         ap = a("sign");
         aq = a("wooden_door");
         ar = a("spruce_door");
         as = a("birch_door");
         at = a("jungle_door");
         au = a("acacia_door");
         av = a("dark_oak_door");
         BUCKET = a("bucket");
         ax = a("water_bucket");
         ay = a("lava_bucket");
         az = a("minecart");
         aA = a("saddle");
         aB = a("iron_door");
         aC = a("redstone");
         aD = a("snowball");
         aE = a("boat");
         aF = a("leather");
         aG = a("milk_bucket");
         aH = a("brick");
         aI = a("clay_ball");
         aJ = a("reeds");
         aK = a("paper");
         aL = a("book");
         aM = a("slime_ball");
         aN = a("chest_minecart");
         aO = a("furnace_minecart");
         aP = a("egg");
         aQ = a("compass");
         aR = (ItemFishingRod)a("fishing_rod");
         aS = a("clock");
         aT = a("glowstone_dust");
         aU = a("fish");
         aV = a("cooked_fish");
         aW = a("dye");
         aX = a("bone");
         aY = a("sugar");
         aZ = a("cake");
         ba = a("bed");
         bb = a("repeater");
         bc = a("cookie");
         bd = (ItemWorldMap)a("filled_map");
         be = (ItemShears)a("shears");
         bf = a("melon");
         bg = a("pumpkin_seeds");
         bh = a("melon_seeds");
         bi = a("beef");
         bj = a("cooked_beef");
         bk = a("chicken");
         bl = a("cooked_chicken");
         bm = a("mutton");
         bn = a("cooked_mutton");
         bo = a("rabbit");
         bp = a("cooked_rabbit");
         bq = a("rabbit_stew");
         br = a("rabbit_foot");
         bs = a("rabbit_hide");
         bt = a("rotten_flesh");
         bu = a("ender_pearl");
         bv = a("blaze_rod");
         bw = a("ghast_tear");
         bx = a("gold_nugget");
         by = a("nether_wart");
         POTION = (ItemPotion)a("potion");
         bA = a("glass_bottle");
         bB = a("spider_eye");
         bC = a("fermented_spider_eye");
         bD = a("blaze_powder");
         bE = a("magma_cream");
         bF = a("brewing_stand");
         bG = a("cauldron");
         bH = a("ender_eye");
         bI = a("speckled_melon");
         bJ = a("spawn_egg");
         bK = a("experience_bottle");
         bL = a("fire_charge");
         BOOK_AND_QUILL = a("writable_book");
         WRITTEN_BOOK = a("written_book");
         bO = a("emerald");
         bP = a("item_frame");
         bQ = a("flower_pot");
         bR = a("carrot");
         bS = a("potato");
         bT = a("baked_potato");
         bU = a("poisonous_potato");
         bV = (ItemMapEmpty)a("map");
         bW = a("golden_carrot");
         bX = a("skull");
         bY = a("carrot_on_a_stick");
         bZ = a("nether_star");
         ca = a("pumpkin_pie");
         cb = a("fireworks");
         cc = a("firework_charge");
         cd = (ItemEnchantedBook)a("enchanted_book");
         ce = a("comparator");
         cf = a("netherbrick");
         cg = a("quartz");
         ch = a("tnt_minecart");
         ci = a("hopper_minecart");
         cj = (ItemArmorStand)a("armor_stand");
         ck = a("iron_horse_armor");
         cl = a("golden_horse_armor");
         cm = a("diamond_horse_armor");
         cn = a("lead");
         co = a("name_tag");
         cp = a("command_block_minecart");
         cq = a("record_13");
         cr = a("record_cat");
         cs = a("record_blocks");
         ct = a("record_chirp");
         cu = a("record_far");
         cv = a("record_mall");
         cw = a("record_mellohi");
         cx = a("record_stal");
         cy = a("record_strad");
         cz = a("record_ward");
         cA = a("record_11");
         cB = a("record_wait");
         cC = a("prismarine_shard");
         cD = a("prismarine_crystals");
         cE = a("banner");
      }
   }
}
